version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
      - 8080:80
    container_name: php
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    container_name: mysql